export const ENV = {
  API_URL: process.env.NEXT_PUBLIC_API_URL || "",

  // TOSS
  TOSS_CLIENT_KEY: process.env.NEXT_PUBLIC_TOSS_CLIENT_KEY || "",

  // KAKAO
  KAKAO_JS_KEY: process.env.NEXT_PUBLIC_KAKAO_JS_KEY || "",
  KAKAO_REDIRECT_URL: process.env.NEXT_PUBLIC_KAKAO_REDIRECT_URL || "",

  // GOOGLE
  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || "",
  GOOGLE_REDIRECT_URL: process.env.NEXT_PUBLIC_GOOGLE_REDIRECT_URL || "",

  // NAVER
  NAVER_CLIENT_ID: process.env.NEXT_PUBLIC_NAVER_CLIENT_ID || "",
  NAVER_REDIRECT_URL: process.env.NEXT_PUBLIC_NAVER_REDIRECT_URL || "",
  NAVER_STATE: process.env.NEXT_PUBLIC_NAVER_STATE || "",
};
